var searchData=
[
  ['save_20pcd_20data_0',['5.2. Save PCD data',['../TurtleBotExample.html#autotoc_md31',1,'']]],
  ['serial_20connection_1',['4.1. Serial Connection',['../TurtleBotExample.html#autotoc_md26',1,'']]],
  ['serialcommunication_2',['serialcommunication',['../classflexxlam_1_1SerialCommunication.html',1,'flexxlam::SerialCommunication'],['../classflexxlam_1_1SerialCommunication.html#ab936236b3a30c04d6ebe5bceac98d553',1,'flexxlam::SerialCommunication::SerialCommunication()']]],
  ['serialize_3',['serialize',['../namespaceflexxlam__msgs.html#a7958f5251a6cb942269905ac2da36ede',1,'flexxlam_msgs::serialize(const PointCloud2 &amp;pointcloud, bool compress=false)'],['../namespaceflexxlam__msgs.html#ac2ecf4b7c50693f4a7514611ee62ed10',1,'flexxlam_msgs::serialize(const Odometry &amp;odom)']]],
  ['set_5fcallback_4',['set_callback',['../classflexxlam_1_1SerialCommunication.html#aa40f9d8ad4038697c6fa09ab9f5b8c91',1,'flexxlam::SerialCommunication::set_callback(std::function&lt; void(std::vector&lt; uint8_t &gt;)&gt; callback)'],['../classflexxlam_1_1SerialCommunication.html#af4a1c1a9f5ef2b74502c31ca909465f1',1,'flexxlam::SerialCommunication::set_callback(void(T::*fp)(M), T *obj)'],['../classflexxlam_1_1UDPCommunication.html#a53a8445f77e333806cbe519fd0c7d228',1,'flexxlam::UDPCommunication::set_callback(std::function&lt; void(std::vector&lt; uint8_t &gt;)&gt; callback)'],['../classflexxlam_1_1UDPCommunication.html#a98454992bfb70c4eb4b266d5651b70f2',1,'flexxlam::UDPCommunication::set_callback(void(T::*fp)(M), T *obj)']]],
  ['setethernetcommunicationconfigprotocol_5',['setethernetcommunicationconfigprotocol',['../classflexxlam_1_1SetEthernetCommunicationConfigProtocol.html',1,'flexxlam::SetEthernetCommunicationConfigProtocol'],['../classflexxlam_1_1SetEthernetCommunicationConfigProtocol.html#a0607bafbb372a261703af725d74a2f7e',1,'flexxlam::SetEthernetCommunicationConfigProtocol::SetEthernetCommunicationConfigProtocol(const vector&lt; uint8_t &gt; &amp;bytes, bool payload_only=false)'],['../classflexxlam_1_1SetEthernetCommunicationConfigProtocol.html#acd195aee4e5455982bb08ccc58317dfa',1,'flexxlam::SetEthernetCommunicationConfigProtocol::SetEthernetCommunicationConfigProtocol(bool enabled, uint32_t port)']]],
  ['setlidarconfigprotocol_6',['setlidarconfigprotocol',['../classflexxlam_1_1SetLidarConfigProtocol.html#a85adc12ebd5e3a4021a77a77a33b3bef',1,'flexxlam::SetLidarConfigProtocol::SetLidarConfigProtocol()'],['../classflexxlam_1_1SetLidarConfigProtocol.html',1,'flexxlam::SetLidarConfigProtocol'],['../classflexxlam_1_1SetLidarConfigProtocol.html#a6d2fd52b5c587e77d4807c46d94100ec',1,'flexxlam::SetLidarConfigProtocol::SetLidarConfigProtocol(std::string lidar_type)'],['../classflexxlam_1_1SetLidarConfigProtocol.html#a9da5af5c2cccdde48bb4b98cdbe1ef01',1,'flexxlam::SetLidarConfigProtocol::SetLidarConfigProtocol(const vector&lt; uint8_t &gt; &amp;bytes, bool payload_only=false)']]],
  ['setmavlinkcommunicationconfigprotocol_7',['setmavlinkcommunicationconfigprotocol',['../classflexxlam_1_1SetMavlinkCommunicationConfigProtocol.html#a64dc6fff0dd0e1fc8ea7efba0ff91a50',1,'flexxlam::SetMavlinkCommunicationConfigProtocol::SetMavlinkCommunicationConfigProtocol()'],['../classflexxlam_1_1SetMavlinkCommunicationConfigProtocol.html',1,'flexxlam::SetMavlinkCommunicationConfigProtocol'],['../classflexxlam_1_1SetMavlinkCommunicationConfigProtocol.html#af6fd95313595f0ba356bcb3308d0277d',1,'flexxlam::SetMavlinkCommunicationConfigProtocol::SetMavlinkCommunicationConfigProtocol()']]],
  ['setserialcommunicationconfigprotocol_8',['setserialcommunicationconfigprotocol',['../classflexxlam_1_1SetSerialCommunicationConfigProtocol.html#a52c7590f068f76ba55dc0e5543e23942',1,'flexxlam::SetSerialCommunicationConfigProtocol::SetSerialCommunicationConfigProtocol()'],['../classflexxlam_1_1SetSerialCommunicationConfigProtocol.html',1,'flexxlam::SetSerialCommunicationConfigProtocol'],['../classflexxlam_1_1SetSerialCommunicationConfigProtocol.html#abee7908e23ad1a7ed9930e00b794c433',1,'flexxlam::SetSerialCommunicationConfigProtocol::SetSerialCommunicationConfigProtocol()']]],
  ['setting_9',['LiDAR Setting',['../LiDARSetting.html',1,'']]],
  ['setup_10',['setup',['../TurtleBotExample.html#autotoc_md17',1,'1.1. Hardware setup'],['../TurtleBotExample.html#autotoc_md19',1,'1.2. Driver setup']]],
  ['setup_20ardupilot_11',['1.1. Setup Ardupilot',['../ArdupilotExample.html#autotoc_md2',1,'']]],
  ['setup_20environment_12',['setup environment',['../ArdupilotExample.html#autotoc_md1',1,'1. Setup environment'],['../PX4Example.html#autotoc_md9',1,'1. Setup environment']]],
  ['setup_20px4_13',['1.1. Setup PX4',['../PX4Example.html#autotoc_md10',1,'']]],
  ['setup_20raspberry_20pi_20for_20turtlebot_14',['1.1.1. Setup raspberry pi for TurtleBot',['../TurtleBotExample.html#autotoc_md18',1,'']]],
  ['setup_20the_20environment_15',['1. Setup the environment',['../TurtleBotExample.html#autotoc_md16',1,'']]],
  ['stop_16',['stop',['../classflexxlam_1_1SerialCommunication.html#a1e21e2041da226e00ae631381d02c596',1,'flexxlam::SerialCommunication::stop()'],['../classflexxlam_1_1UDPCommunication.html#a4f58ee977e7f78faa7c1b1fb354389e4',1,'flexxlam::UDPCommunication::stop()']]],
  ['subscriber_20example_20for_20flexxlam_20data_17',['5.1. Subscriber example for FlexXlam data',['../TurtleBotExample.html#autotoc_md30',1,'']]]
];
